org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
java_version=21

fabric_loader_version=0.19.4
fabric_api_version=0.116.15+1.21.1
neo_version=21.1.228
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=raise_resurrection_ascend
mod_name=Raise & Resurrection & Ascend
mod_license=GPL-3.0-or-later
mod_version=1.0.6
mod_group_id=dev.rinchan
mod_authors=RinChan
mod_description=A server-authoritative downed state with damage vulnerability, healing recovery, and native Totem of Undying protection.
